 
apiVersion: backstage.io/v1alpha1
kind: API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: ./openapi.yaml
metadata:
  name: code-with-quarkus-api
--- 
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: application
  lifecycle: production
  owner: user:guest
  providesApis:
  - code-with-quarkus-api
metadata:
  name: code-with-quarkus
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.quarkus.io/version: 3.17.3
  annotations:
    backstage.io/source-location: url:https://github.com/iocanel/code-with-quarkus
  tags:
  - java
  - quarkus
